### ISSUE TITLE
Add more tests/examples

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-command#11]
Luke:
- [ ] Clustering (use a shell script instead of inline command)
- [x] Invoking the lambda using `aws lambda invoke` (may require env vars for credentials, etc.)
- [x] curl for managing external SaaS (GitHub labels?)

Laura:
- [x] Provisioner in examples repo
- [ ] Ansible? (Or Chef, etc.)
- [x] `kubectl` command?

Ian:
- [ ] Templating?  (Assets/archives)

**Comment by nimbinatus** [comment]
The remote Ansible example has been breaking in my builds due to either an error with GCP or an error with Ansible itself. There's a very simple local command example I've pushed up, but I'd like to see the remote one working before we call it a real example.

**Comment by lukehoban** [comment]
Closing this out - as we now have a good collection of examples here.  More are always welcome though!
