### ISSUE TITLE
`Inputs.ConnectionArgs.PrivateKey` leaks private keys in plain text by default

### ISSUE THREAD

**Issue by Smaug123** [pulumi/pulumi-command#111]
### What happened?

The easiest way to use the `PrivateKey` feature of `ConnectionArgs` will leak your private key into the `connection` property of the resulting `Command`'s resource (specifically the `privateKey` of the JSON blob of that value).

### Steps to reproduce

F# to construct a `Command` which will leak your private key if you run it:

```fsharp
module PulumiWebServer.Thing

open Pulumi.Command.Remote

let conn =
    let inputArgs = Inputs.ConnectionArgs ()

    inputArgs.Host <- "192.168.0.1"
    inputArgs.Port <- 22.0
    inputArgs.User <- "root"
    inputArgs.PrivateKey <- System.IO.File.ReadAllText "~/.ssh/id_ed25519"
    inputArgs

let bad_command () =
    let args = CommandArgs ()
    args.Connection <- conn
    args.Create <- "echo hello"

    Command ("oh-no", args)
```

### Expected Behavior

The `connection` property to contain a hash of my private key.

### Actual Behavior

The `connection` property contained my private key in plain text.

### Versions used

```
pulumi about
CLI          
Version      3.35.2
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME          VERSION
cloudflare    4.8.0
command       0.4.1
digitalocean  4.14.0
dotnet        unknown

Host     
OS       darwin
Version  12.4
Arch     arm64

This project is written in dotnet: executable='/nix/store/ypjjp011l3crp0m3wmp1xbwxn5q5xpdr-dotnet-sdk-6.0.301/bin/dotnet' version='6.0.301'

Current Stack: dev

TYPE                                URN
pulumi:pulumi:Stack                 urn:pulumi:dev::PulumiWebServer::pulumi:pulumi:Stack::PulumiWebServer-dev
pulumi:providers:digitalocean       urn:pulumi:dev::PulumiWebServer::pulumi:providers:digitalocean::default_4_14_0
digitalocean:index/sshKey:SshKey    urn:pulumi:dev::PulumiWebServer::digitalocean:index/sshKey:SshKey::default
digitalocean:index/droplet:Droplet  urn:pulumi:dev::PulumiWebServer::digitalocean:index/droplet:Droplet::nixos-server
pulumi:providers:cloudflare         urn:pulumi:dev::PulumiWebServer::pulumi:providers:cloudflare::default_4_8_0
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::www-cname
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::nextcloud-ipv6
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::nextcloud-ipv4
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::gitea-ipv6
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::gitea-ipv4
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::patrickstevens.co.uk-ipv6
cloudflare:index/record:Record      urn:pulumi:dev::PulumiWebServer::cloudflare:index/record:Record::patrickstevens.co.uk-ipv4
pulumi:providers:command            urn:pulumi:dev::PulumiWebServer::pulumi:providers:command::default_0_4_1
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::nix-infect
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-nginx-config
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-user-config
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-nextcloud-config
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-gitea-config
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-nginx
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-users
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-nextcloud-nix
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-nextcloud
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-nextcloud-user
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-gitea-password
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::write-gitea-password
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::configure-gitea
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::reboot-post-infect
command:remote:Command              urn:pulumi:dev::PulumiWebServer::command:remote:Command::nixos-rebuild


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/Smaug123
User           Smaug123
Organizations  Smaug123, fsprojects

Dependencies:
NAME                 VERSION
FSharp.Core          6.0.5
Pulumi               3.37.2
Pulumi.Cloudflare    4.8.0
Pulumi.Command       0.4.1
Pulumi.DigitalOcean  4.14.0
```

### Additional context

This behaviour is implied by the documentation, though it's not explicitly stated next to `PrivateKey`: any `Input` which is not explicitly made secret via `Output.CreateSecret` is not secret. But I think a user would reasonably expect a first-class feature of the API, which is designed only to consume secrets, to be secure by default. At the very least, it should be documented in big letters in the docstring that the user must explicitly make this secret, although in my view it's a bug in *any* library if there's a feature that the user must simply remember can't be used without taking some other action.

Before using the feature and discovering that I was wrong, I confidently predicted that since this `PrivateKey` would only be used for change detection and didn't need to be transmitted to a different machine, Pulumi would just hash it.

@frassle notes that a longer-term architectural fix could be https://github.com/pulumi/pulumi/issues/9107 .

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
I've opened https://github.com/pulumi/pulumi/issues/10319 to track the feature that would enable doing this "by default".

In the meantime, `Output.CreateSecret` can be used to ensure that the value read from disk is a secret. The secrets model and the need for this call in this case are discussed in https://www.pulumi.com/docs/intro/concepts/secrets/#programmatically-creating-secrets.

I believe this issue should track ensuring that all documentation explicitly mentions the need for `Output.CreateSecret`/`pulumi.secret` if the value for this is read from disk (which is somewhat common here).  https://github.com/pulumi/pulumi/issues/10319 tracks adding support for a feature to allow annotating this input as requiring a secret without the need for the conversion.

**Comment by AaronFriel** [comment]
I commented on pulumi/pulumi#10319 suggesting we create a `SecretCommand` resource that marks all inputs and outputs as secret at the schema level, which should mitigate this and mitigate the risk that users might fail to mark a particular value as secret.
