### ISSUE TITLE
Delete state causes golang runtime to panic when removed from source

### ISSUE THREAD

**Issue by JoseAlban** [pulumi/pulumi-command#117]
### What happened?

I created a delete command like this:
```
    create     : "/my/bin arg1 arg2"
    delete     : "/my/bin arg1 arg2"
```

then pulumi up'ed it.
after, I had to refactor and removed `/my/bin` and removed the entire command resource from pulumi as well.
I expected pulumi destroy to bring the stack down gracefully, but instead pulumi crashed with panic.

### Steps to reproduce

1. delete command like this:
```
    create     : "/my/bin arg1 arg2"
    delete     : "/my/bin arg1 arg2"
```

2. /my/bin exists
3. pulumi up
4. delete command resource on pulumi
5. delete /my/bin
6. pulumi destroy

panics 

### Expected Behavior

not panic, graceful shutdown, maybe with warning that bin not found

### Actual Behavior

panic

### Versions used

CLI
Version      3.36.0
Go Version   go1.17.11
Go Compiler  gc

Host
OS       darwin
Version  11.6
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @JoseAlban 

I am going to close this out - I can't recreate it. If you can give me a little more information to recreate this, I will come back and reopen it

Thanks

Paul
