### ISSUE TITLE
A command that writes to stderr gives confusing Pulumi output

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-command#121]
Given the following Pulumi program:

```typescript
import * as command from "@pulumi/command";

new command.local.Command("docker-build", {
  create: "echo \"hello world\" >&2"
});
```

I get the following output:

```bash
$ pulumi up -y
Previewing update (dev)

View Live: https://app.pulumi.com/jkodroff/try-docker-command/dev/previews/24f5e5f1-1143-413e-b6d1-736b7f34fefc

     Type                      Name                    Plan
 +   pulumi:pulumi:Stack       try-docker-command-dev  create
 +   └─ command:local:Command  docker-build            create

Resources:
    + 2 to create

Updating (dev)

View Live: https://app.pulumi.com/jkodroff/try-docker-command/dev/updates/27

     Type                      Name                    Status                  Info
 +   pulumi:pulumi:Stack       try-docker-command-dev  created
 +   └─ command:local:Command  docker-build            **creating failed**     1 error

Diagnostics:
  command:local:Command (docker-build):
    error: hello world

Resources:
    + 2 created

Duration: 2s
```

The output is confusing because the stack tree shows an error, but the `Resources:` summary shows success. Pulumi itself also returns 0.

I ran into this because `docker build` outputs to stderr. Per [this issue](https://github.com/moby/buildkit/issues/1186#issuecomment-1090427273), it looks like printing logs to stderr is common in many *nix tools (to my surprise).

If indeed printing progress messages to stderr is common, I think we need to ensure that by default, stderr output on `local.Command` does not display as an error in Pulumi. We may also want to consider an option in the Command resource to keep the existing behavior.

**Comment by dixler** [comment]
pulumi also doesn't display which output is stderr or an info log message and makes the output ambigious.
