### ISSUE TITLE
Strange/wrong version for nuget package

### ISSUE THREAD

**Issue by sloncho** [pulumi/pulumi-command#130]
### What happened?

Looking at the releases, 0.5.2 was produced 2 days ago. There is a nuget package with that version too.

At the same time, there is a nuget package version 4.5.0 (and 4.6.0-alpha) as well. They are older than 0.5.2, but package managers pick them as latest version.

### Steps to reproduce

See available version here: https://www.nuget.org/packages/Pulumi.Command/#versions-body-tab

### Expected Behavior

1. 4.5.0 to not exists?
2. 4.x versions to actually contain latest code?

### Actual Behavior

older (by time) but higher version numbers exist

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
Thanks for bringing that to our attention, working to get it resolved now!

**Comment by jkisk** [comment]
These are deprecated now (the 4.x.x versions) and 0.5.2 should now be picked up as latest.

**Comment by sloncho** [comment]
That was fast response. Unfortunately, this made package managers to report the whole package deprecated :(

**Comment by stack72** [comment]
Hey @sloncho we will remove that deprecation warning to make that less of a problem
