### ISSUE TITLE
Allow usage of bastion host for remote.NewCommand

### ISSUE THREAD

**Issue by nicklasfrahm** [pulumi/pulumi-command#131]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently it is not possible to execute a `remote.NewCommand` using a bastion host. This could be very useful for more advanced scenarios, where one would like to use Pulumi to replace `ansible`.

### Affected area/feature

The `remote.NewCommand` resource. I will submit a PR shortly with a potential implementation.

**Comment by stack72** [comment]
Hi @nicklasfrahm 

Thanks for the great feature request here - the team will look at when they can get to add this

Paul

**Comment by nicklasfrahm** [comment]
@stack72 I submitted a PR. I would need guidance as to how I can test this in isolation.

**Comment by nobitran** [comment]
Please implement this feature. In Terraform I can connect into Private Server (through Bastion Server). I access and run some commands on Private Server. Please implement this function. Thanks a lot.

**Comment by iwahbe** [comment]
Fixed by https://github.com/pulumi/pulumi-command/pull/269, largely due to @eBeyond and @nicklasfrahm!
