### ISSUE TITLE
Command output to be secret

### ISSUE THREAD

**Issue by sloncho** [pulumi/pulumi-command#134]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We are using a command to call a third party service, which generates secrets. Storing the StdOut and StdErr in plain text in the stack exposes these secrets. I'm not sure about possible approach - but coming from c# land, exposing these outputs as "virtual" can allow inheritors of the command component to lock them. Or possibly some always "secret". Or some parameter on the args to allow "locking" the outputs.

**Comment by sloncho** [comment]
As we can set "[additionalsecrets](https://www.pulumi.com/docs/intro/concepts/resources/options/additionalsecretoutputs/)" on the resource options, which solves our issue, maybe setting these to secrets by default can be a good idea.

**Comment by danielrbradley** [comment]
Yes, I think setting `AdditionalSecretOutputs` is sufficient here. Will close as not needed as a resource-specific argument 👍
