### ISSUE TITLE
command.local.Triggers docs are empty

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-command#153]
### What happened?

command.local.Triggers has no docs, so I don't have any idea how it works: https://www.pulumi.com/registry/packages/command/api-docs/local/command/#triggers_nodejs

### Steps to reproduce

n/a

### Expected Behavior

Docs

### Actual Behavior

No docs

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
It's in the schema, but doesn't seem to be emitted in docsgen.

https://github.com/pulumi/pulumi-command/blob/25825b86639ef19b63726a13f9819d3d9f597da1/provider/cmd/pulumi-resource-command/schema.json#L79-L85

Thanks for filing.

**Comment by lukehoban** [comment]
It is available now:

<img width="1198" alt="Screenshot 2022-12-28 at 1 15 01 PM" src="https://user-images.githubusercontent.com/223467/209891469-75719df4-2739-49cd-9524-c857562f01e2.png">
