### ISSUE TITLE
Add support for bastion-based connections

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-command#16]
There are cases where the connection to a remote host must be established via a bastion.  We could add support for this in the `remote.Connection` args.

**Comment by AMKamel** [comment]
That's pretty much needed

**Comment by JamesMilneFilmlight** [comment]
Another plus 1 for this, my existing code using the paramiko-based provider in Python uses the 'gateway' parameter to proxy SSH connections.

**Comment by jsbrain** [comment]
Absolutely, this should be highest priority in my opinion.

**Comment by taylorific** [comment]
+1

**Comment by thomas11** [comment]
This is a duplicate of #131 and was implemented by #269.
