### ISSUE TITLE
`pulumi up --refresh` uses output.dir instead of inputs.dir to lookup the resource location

### ISSUE THREAD

**Issue by rajiteh** [pulumi/pulumi-command#160]
### What happened?

Possibly related to #129

It looks like the the dir check (and may be script re-invocation?) is performed during pulumi refresh operations as well. While it should be generally ok to re-run the command as it is expected to be idempotent, but by using values stored in the stack to perform the refresh breaks certain workflows. I ran in to a situation where where I created the stack in my local computer and tried to refresh it in CI and it failed because the `dir` I used locally to include a file in the same repo (by using `__dirname`) wasn't the same as it is in the CI environment.

### Steps to reproduce

Create a script in the pulumi project path
```
mkdir -p scripts/
printf '#!/bin/bash\necho hello\n' > scripts/test.sh 
chmod +x scripts/test.sh
```

Inside pulumi, create a command resource and and apply the stack.

```node
new command.local.Command(`myCommand`, {
            create: "scripts/test.sh",
            dir: __dirname,
        }, { parent: this });
```

Now move (not copy) the repo to a different location, and try to run `pulumi up --refresh `

### Expected Behavior

It should use the `inputs.dir` to set the dir for the refresh instead of `outputs.dir`

### Actual Behavior

It tries to look up the old path which is missing and produces this error

```
Diagnostics:
  command:local:Command (myCommand):
    error: error looking up directory: "stat /home/user/projects/pulumi-proj/scripts: no such file or directory"
```

### Output of `pulumi about`

CLI          
Version      3.44.2
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
command     0.5.2

### Additional context

May be there is a better way to specify files that are included inside repo instead of using `__dirname` ? -- Using relative paths seems risky here as well. May be a special option that will pin the `dir` to the root of pulumi execution? 

Is there any way to prevent pulumi.Command from being refreshed at all once created? Specially when the user sends in `create:` command only?

Thanks!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @rajiteh! I tried to reproduce this but wasn't able to, so far.

```
$ pulumi up
Previewing update (dev)

     Type                      Name                    Plan
 +   pulumi:pulumi:Stack       repro-move-command-dev  create
 +   └─ command:local:Command  myCommand               create

Outputs:
    output: output<string>

Resources:
    + 2 to create

Do you want to perform this update? yes
Updating (dev)

     Type                      Name                    Status
 +   pulumi:pulumi:Stack       repro-move-command-dev  created (0.73s)
 +   └─ command:local:Command  myCommand               created (0.24s)

Outputs:
    output: "hello"

Resources:
    + 2 created

Duration: 2s

$ mv repro-move-command repro-move-command-new

$ cd repro-move-command-new

$ pulumi up --refresh
Please choose a stack, or create a new one: dev
Previewing update (dev)

     Type                      Name                    Plan       Info
     pulumi:pulumi:Stack       repro-move-command-dev
 ~   └─ command:local:Command  myCommand               update     [diff: ~dir]

Outputs:
  ~ output: "hello" => output<string>

Resources:
    ~ 1 to update
    1 unchanged

Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/thomas11/repro-move-command/dev/updates/2

     Type                      Name                    Status              Info
     pulumi:pulumi:Stack       repro-move-command-dev   (0.27s)
 ~   └─ command:local:Command  myCommand               updated (0.10s)     [diff: ~dir]

Outputs:
    output: "hello"

Resources:
    ~ 1 updated
    1 unchanged

Duration: 1s
```

The only difference I can see is that I removed `{ parent: this }` from your Command.

My whole program looks like this:

```typescript
import { local } from "@pulumi/command";

const cmd = new local.Command(`myCommand`, {
    create: "scripts/test.sh",
    dir: __dirname,
});

export const output = cmd.stdout
```

**Comment by rajiteh** [comment]
Seems to have been a transient issue. I'm unable to reproduce as well. May be it was an I had an `ignoreChanges` on `dir` arg at one point, perhaps that confused pulumi.

Thanks for looking in to it. Closing.
