### ISSUE TITLE
Clean up sdk-gen

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-command#165]
SDK generation can be done using only the provider binary. This means that we can remove the Schema generation code and simplify the build process.

**Comment by thomas11** [comment]
We're generating the SDK now directly through the pulumi CLI: `$(PULUMI) package gen-sdk --language python $(SCHEMA_FILE)`. That does require the schema file, but it's just retrieved from the provider binary, with a single invocation of pulumi: `$(PULUMI) package get-schema $(WORKING_DIR)/bin/${PROVIDER}`. Closing as implemented.
