### ISSUE TITLE
regression on command 0.7.0: stdout can not be loaded as json using json.loads()

### ISSUE THREAD

**Issue by wuxxin** [pulumi/pulumi-command#166]
### What happened?

- command plugin updated from 0.6.0 to 0.7.0
- pulumi up aborts with error message that it can not parse the supposed json string at char 0 line 0
- downgrading command to 0.6.0 and modifying pulumi stack with the resourceid and version of the old command plugin fixes the issue

### Steps to reproduce

the corresponding code snippet is as following:

```python
vault_ca = command.local.Command(
    "{}_vault_ca".format(name),
    create="./__vault_pipe.sh --yes",
    stdin=json.dumps(vault_config),
    opts=pulumi.ResourceOptions(
        parent=self,
        additional_secret_outputs=["stdout"],
        protect=True,
        # XXX make pulumi find legacy name for ca_factory_fault_ca
        aliases=[Alias(name="vault_ca")] if name == "ca_factory" else [],
    ),
)
ca_secrets = vault_ca.stdout.apply(lambda x: json.loads(x))
```

pulumi fails on ca_secret = ... while trying lambda x: json.loads(x)

it is probably reproducable by calling any external command, which should return a json formatted output to be parse by pulumi

### Expected Behavior

same functionality as 0.6.0

### Actual Behavior

pulumi bails out while trying to read stdout of the command as json

### Output of `pulumi about`

CLI
Version      3.46.1
Go Version   go1.19.3
Go Compiler  gc

Host
OS       arch
Version  22.0.0
Arch     x86_64

Backend
Name           power
URL            file:///home/wuxxin/code/athome/state/pulumi
User           wuxxin
Organizations

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@dixler Could you please take a look?

**Comment by AMKamel** [comment]
I have the same issue

**Comment by dixler** [comment]
Hi. Thanks @wuxxin for filing the issue with the repro code (it helped me write a test case) and @AMKamel for the context it really helped narrow down what was going on. When moving from 0.6.0 to 0.7.0, fields being computed were dropped and that explains why it was misbehaving in preview.

This is an issue in the pulumi-go-provider library. I have opened https://github.com/pulumi/pulumi-go-provider/issues/75 to track this.

**Comment by jkodroff** [comment]
I'm seeing spurious quote marks around `command.local.Command.stdout` which is causing a similar issue with JSON parsing (in my case, from an AWS CLI command).

**Comment by iwahbe** [comment]
We can simply the repro a bit. Given the following program:
```ts
import { local } from "@pulumi/command";

const cmd = new local.Command("json", {
  create: `echo '{"json": true}'`,
});

export const parsed = cmd.stdout.apply(JSON.parse);
```

`pulumi preview` fails with:
```sh
  pulumi:pulumi:Stack (ts-dev):
    error: Running program '$DIR' failed with an unhandled exception:
    SyntaxError: Unexpected end of JSON input
```

`pulumi up --skip-preview` succeeds.

**Comment by AMKamel** [comment]
Are we expecting a fix here by this merge?
https://github.com/pulumi/pulumi-go-provider/pull/105#pullrequestreview-1589460460
