### ISSUE TITLE
warning: Missing expect call to 'Check' before 'Diff' for resource "xyz"

### ISSUE THREAD

**Issue by sebthom** [pulumi/pulumi-command#173]
### What happened?

When updating a stack I recently get a warning for all affected command resources
` warning: Missing expect call to 'Check' before 'Diff' for resource "urn:pulumi:<REMOVED>$command:remote:Command::<REMOVED>"` 

### Steps to reproduce

Create a pulumi stack with command resources that have triggers configured.

### Expected Behavior

Either the warning is not shown or an actionable/user-friendly message is shown.

### Actual Behavior

Cryptic warnings are shown.

### Output of `pulumi about`

CLI
Version      3.50.2
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME        VERSION
command     0.7.0
command     0.7.0
command     0.7.0
command     0.7.0
kubernetes  3.23.1
nodejs      unknown
vsphere     4.3.0

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in nodejs: executable='<REMOVED>node.exe' version='v18.12.1'

### Additional context

The warning is generated here: https://github.com/pulumi/pulumi-go-provider/blob/996b11838d4b550a817c8015efa512564cb8c13b/infer/resource.go#L446

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hi thanks for filing this and for the digging. You are correct, this appears to be caused by the pulumi-go-provider library.

I've opened an issue to track this there https://github.com/pulumi/pulumi-go-provider/issues/77
