### ISSUE TITLE
Invalid provider version: v4.5.0

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-command#183]
It appears that we [erroneously published a `v4.5.0` tagged release last year](https://github.com/pulumi/pulumi-command/actions/workflows/release.yml).

This provider is in preview, and on `v0.7.0`.

We've had a [user report an error](https://github.com/pulumi/pulumi-command/issues/182) on "`v4.5.0"` and so it appears that we should find a way to pull or otherwise mark as invalid this particular version from our package registries.

Related: https://docs.google.com/document/d/1EyYLKoO5fwmb-9rZxCBD5_ACk9aObcyOKjS5733I8r4/edit

**Comment by AaronFriel** [comment]
Keeping this issue open pending resolution of the Java SDK (Maven) ticket.

**Comment by AaronFriel** [comment]
Maven resolved this by removing the 4.x artifacts.
