### ISSUE TITLE
Non-hermetic builds due to implicit pulumi gen-sdk updates

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-command#184]
### What happened?

Running acceptance tests on https://github.com/pulumi/pulumi-command/pull/180 noticing that the generated code bit-rotted due to implicit upgrades of Pulumi CLI and therefore SDK code generation for Go, and checks are now failing. 

I can work around by updating the codegen to be in line with the latest version for now. In the future we can resolve this either by pining the CLI but having a workflow that upgrades its versions via PRs (probably ideal - the most explicit), or some compromise like a nightly workflow that stands up PRs to re-gen the SDKs on the latest current version and maybe even auto-merges them if tests pass.

### Expected Behavior

Passing acceptance tests.

### Steps to reproduce

Pulumi upgrades that change codegen.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@t0yv0 Did https://github.com/pulumi/pulumi-command/pull/262 fix this issue?

**Comment by t0yv0** [comment]
Yes actually good catch.
