### ISSUE TITLE
`run` does not return stdout or stderr

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi-command#198]
### What happened?

See https://github.com/pulumi/pulumi/discussions/13013#discussioncomment-5996365 for initial user report on this.
I've tried repro'ing myself and can confirm that stdout and stderr are returned empty even for simple commands such as `echo hi`.

### Expected Behavior

stdout and stderr to contain the output of the command ran.

### Steps to reproduce

```
import * as command from "@pulumi/command";

// Render the Shell Script
const renderShell1 = command.local.run({
    command: "echo hello",
    environment: {
        //IMAGE_URL: imageurl,
        IMAGE_URL: "test123",
    },
  });
export const stdo = renderShell1.then(v => v.stdout);
export const stde = renderShell1.then(v => v.stderr);
```

### Output of `pulumi about`

`@pulumi/command  0.7.2`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
@dixler would you be able to take a look at this as a command provider expert 😬
