### ISSUE TITLE
Remote Command should fail if connectivity to remote host can not be established

### ISSUE THREAD

**Issue by trylvis** [pulumi/pulumi-command#199]
### What happened?

Trying to use Remote Command, connecting to a dummy ip like "8.8.8.8" with random credentials, do not fail, however keeps running for a long while.

Would expect it to fail with some error cannot connect to remote host, if it can not connect to the remote machine.

Would it be possible to add some default timeout?

I guess one option of handling it on our end would be to use [Custom Timeouts](https://www.pulumi.com/docs/concepts/options/customtimeouts/) , but that would not be optimal if it is actually running some kind of long running job.

### Expected Behavior

After max 60 seconds throw an error that it cannot connect to the remote host.

### Steps to reproduce

```
# Run a script to update packages on the remote machine.
update_os_cmd = command.remote.Command("updatePythonCmd",
    connection=command.remote.ConnectionArgs(
        host="8.8.8.8",
        port=22,
        user="pirates",
        password="johnnydepp",
    ),
    create="""(sudo apt update -y);
(sudo apt upgrade -y);
""")
```

Output - and counting..:
command:remote:Command  updatePythonCmd   updating (716s)...  [diff: ~connection]

### Output of `pulumi about`

CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.102.0
command       0.7.2
python        unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in python: executable='/home/linuxbrew/.linuxbrew/bin/python3' version='3.11.2
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/x

Dependencies:
NAME                 VERSION
pip                  23.1.2
pulumi-azure-native  1.102.0
pulumi-command       0.7.2
setuptools           67.7.2
wheel                0.40.0

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @trylvis - thank you for filing this issue. We'll take a look as soon as we are able!
