### ISSUE TITLE
Dotnet nuget publish is failing

### ISSUE THREAD

**Issue by zlepper** [pulumi/pulumi-command#205]
### What happened?

Nuget publish is failing due to unsupported image formats: 
```
error: Response status code does not indicate success: 400 (Unsupported icon image format. Only PNG and JPG images are supported.).
```

https://github.com/pulumi/pulumi-command/actions/runs/4491757899/jobs/8273965607

### Expected Behavior

It succeeds

### Steps to reproduce

Look at "Publish SDKs" here: https://github.com/pulumi/pulumi-command/actions/runs/4491757899/jobs/8273965607

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by zlepper** [comment]
Looking at the PNG, it's an SVG file: https://github.com/pulumi/pulumi-command/blob/master/sdk/dotnet/logo.png

Which is not a PNG, so i think Nuget is correct here.

**Comment by AaronFriel** [comment]
@zlepper Thank you for discovering and fixing this!
