### ISSUE TITLE
Failed to publish to nuget

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-command#243]
### What happened?

A release of `pulumi-command` silently failed to publish to nuget:
<img width="1728" alt="Screenshot 2023-07-28 at 11 46 19 AM" src="https://github.com/pulumi/pulumi-command/assets/22222529/e4cc67d9-74f6-4dbb-8b09-8a6bff089b9e">

### Expected Behavior

We successfully publish to nuget. If we fail, we should fail CI.

### Steps to reproduce

Attempt to release `pulumi-command`.

### Output of `pulumi about`

NA

### Additional context

This was found here: https://github.com/pulumi/pulumi-command/issues/205. The fix was to override `logo.png` with an actual PNG. 

https://github.com/pulumi/pulumi-command/pull/235 was the second attempt to fix the issue.

My suspicious is that this script:

https://github.com/pulumi/pulumi-command/blob/f61ae97b3b372b94c254c7d61c5a4582670f72e6/.github/workflows/release.yml#L403-L407

is re-generating the SDK, which results in an unpublishable SDK.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
This failure occurs due to us copying the logo asset after creating the `/sdk/dotnet/bin/Debug/Pulumi.*.nupkg` file. This is the nuget archive that we push to the nuget API, so we'll need to copy the logo asset before creating the archive.
