### ISSUE TITLE
Provider doesn't seem to honor `retainOnDelete`

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-command#244]
In looking into https://github.com/pulumi/pulumi-synced-folder/issues/44, I was assuming that by setting `retainOnDelete: true `, I'd be instructing Pulumi (as the [docs suggest](https://www.pulumi.com/docs/concepts/options/retainondelete/)) "not [to] call through to the resource provider’s `delete` method". The Command provider, however, doesn't seem to honor this setting.

Given an S3 bucket and this TypeScript program (which uses the `managedObjects` property to delegate control over the bucket's files [to the AWS CLI via the Command provider](https://github.com/pulumi/pulumi-synced-folder/blob/9506b2d719a177f64536aa6bd1348e1d792d10de/provider/cmd/pulumi-resource-synced-folder/s3-bucket-folder.ts#L41), I'd expect that after a `pulumi up` and `pulumi destroy`, the bucket would contain the files that'd been synced from `my-folder`:

```typescript
import * as synced from "@pulumi/synced-folder";

const folder = new synced.S3BucketFolder("my-folder", {
    path: "./my-folder",
    bucketName: "my-bucket",
    acl: aws.s3.PrivateAcl,
    managedObjects: false,
}, { retainOnDelete: true });
```

Instead, those files are deleted:

```plain
$ pulumi up

Updating (dev)
...
     Type                                   Name                    Status              
 +   pulumi:pulumi:Stack                    synced-folder-dev       created (0.95s)     
 +   └─ synced-folder:index:S3BucketFolder  my-folder               created (0.60s)     
 +      └─ command:local:Command            my-folder-sync-command  created (1s)        

Resources:
    + 3 created

Duration: 4s

$ aws s3 ls s3://my-bucket
2023-07-31 11:24:52        112 index.html

$ pulumi destroy 

Destroying (dev)
...

     Type                                   Name                    Status           
 -   pulumi:pulumi:Stack                    synced-folder-dev       deleted          
 -   └─ synced-folder:index:S3BucketFolder  my-folder               deleted          
 -      └─ command:local:Command            my-folder-sync-command  deleted (3s)  

$ aws s3 ls s3://my-bucket
[no results]
``` 

Here's a snip from the logs showing the `delete` step being run: 

```
I0731 11:53:51.206716   22698 log.go:81] SnapshotManager: Beginning mutation for step `delete` on resource `urn:pulumi:dev::synced-folder::synced-folder:index:S3BucketFolder::my-folder`
I0731 11:53:51.206743   22698 log.go:81] SnapshotManager.doDelete(urn:pulumi:dev::synced-folder::synced-folder:index:S3BucketFolder::my-folder)
I0731 11:53:51.206754   22698 log.go:81] SnapshotManager.markPendingOperation(urn:pulumi:dev::synced-folder::synced-folder:index:S3BucketFolder::my-folder, deleting)
I0731 11:53:51.374517   22698 log.go:81] StepExecutor worker(1): applying step delete on urn:pulumi:dev::synced-folder::synced-folder:index:S3BucketFolder::my-folder (preview false)
I0731 11:53:51.374577   22698 log.go:81] SnapshotManager: deleteSnapshotMutation.End(..., true)
I0731 11:53:51.374595   22698 log.go:81] SnapshotManager.markOperationComplete(urn:pulumi:dev::synced-folder::synced-folder:index:S3BucketFolder::my-folder)
I0731 11:53:51.374605   22698 log.go:81] Marked old state snapshot as done: urn:pulumi:dev::synced-folder::synced-folder:index:S3BucketFolder::my-folder
I0731 11:53:51.501183   22698 log.go:81] StepExecutor worker(1): step delete on urn:pulumi:dev::synced-folder::synced-folder:index:S3BucketFolder::my-folder retired
```

**Comment by rquitales** [comment]
@cnunciato I believe that `pulumi-synced-folder` is a Pulumi component so the `retainOnDelete` setting shouldn't apply? [Reference documentation link](https://www.pulumi.com/docs/concepts/options/retainondelete/) 

> The retainOnDelete resource option does not apply to component resources, and will not have the intended effect.

**Comment by guineveresaenger** [comment]
Closing this as a no-op.

My recommendation would be to work with provider-level resources for this.

**Comment by cnunciato** [comment]
Although, just to be thorough (and for the docs, as I'd like to make sure they're complete): Are there any plans to support this for components also? Or is there some reason that can't be done?
