### ISSUE TITLE
Add support for watching filesystem for changes to trigger the command

### ISSUE THREAD

**Issue by anatoliykmetyuk** [pulumi/pulumi-command#272]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

My use case is static website deployment to AWS. I use pulumi command to build it locally:

```python
    self.command = Command(f'{name}-static-website-gen',
      create='npm run build',
      delete='rm -rf build',
      dir=cmd_dir,
      environment={
        'PUBLIC_API_ENDPOINT': api.api.url,
      },
      asset_paths=[f"{content_dir}/**"],
      opts=ResourceOptions(parent=self))
```

As you can see, I run `npm run build` from `cmd_dir` where my static website lives. This builds the website into the `content_dir` directory, and later in the pipeline, that directory is uploaded to S3.

Now, if I change some of my static website files, I'd like the website to be rebuilt. However, the `Command` is not aware of changes to those static files, therefore, the website is never rebuilt when I run `pulumi up`.

It would be good to have a parameter in the `Command` to watch a folder for changes, and, if they happen, rerun the task.

## Workaround

To simulate watching filesystem, compute a hash of the target directory and make it a part of the resource name. If the name changes, Pulumi will need to remove the old and create the new resource. You can use e.g. [chacksumdir](https://pypi.org/project/checksumdir/) to do it:

```python
    dir_hash = dirhash(f'{cmd_dir}/src', 'md5')
    self.command = Command(f'{name}-static-website-gen-{dir_hash}',
      create='npm run build',
      dir=cmd_dir,
      environment={
        'PUBLIC_API_ENDPOINT': api.api.url,
      },
      opts=ResourceOptions(parent=self))
```

**Comment by mikhailshilkov** [comment]
Hi @anatoliykmetyuk

I feel like you should also be able to achieve this with the [`triggers`](https://github.com/pulumi/pulumi-command/blob/master/sdk/nodejs/local/command.ts#L345) property. You should pass a hash code or something that changes with the folder, potentially using a `pulumi.Asset`. Could you give that a try?

**Comment by anatoliykmetyuk** [comment]
> Hi @anatoliykmetyuk I feel like you should also be able to achieve this with the [triggers](https://github.com/pulumi/pulumi-command/blob/master/sdk/nodejs/local/command.ts#L345) property. You should pass a hash code or something that changes with the folder, potentially using a pulumi.Asset. Could you give that a try?

Yes, I saw the `triggers` property, but I didn't find any documentation on how to use it or what it does. Could you please give a simple example to get an idea how it works?

**Comment by mikhailshilkov** [comment]
I believe you can provide any value(s) to it. If a value changes between two pulumi runs, the property will trigger a resource replacement. So, if you have a `hash` that you already calculated, it should be as simple as

```py
triggers = [hash],
```
