### ISSUE TITLE
Enhance stdout and stderr reporting

### ISSUE THREAD

**Issue by JacobReynolds** [pulumi/pulumi-command#32]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be awesome if there was a way to define how stderr and stdout are handled. Currently it seems like only the exit status is reported.

### Affected area/feature
@pulumi/command.local
```typescript
import { local } from "@pulumi/command";

new local.Command('test', {
  create: 'command-that-does-not-exist'
});
```

The output currently is
```console
me@home:~$ pulumi up -y --skip-preview
Updating (test):
     Type                      Name       Status                  Info
 +   pulumi:pulumi:Stack       tmp2-test  **creating failed**     1 error
 +   └─ command:local:Command  test       **creating failed**     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (tmp2-test):
    error: update failed
 
  command:local:Command (test):
    error: exit status 127
 
Resources:
    + 1 created

Duration: 2s
```

It would be awesome if some amount of the stderr output would be shown, e.g. `command not found: command-that-does-not-exist`. This may be possible currently with the `stderr` output provided on the object, but I'm not sure how to integrate that into the core CLI output.

**Comment by shinebayar-g** [comment]
Yeah, `stdout`, `stderr` outputs are much needed!

For now you can do `pulumi up --logtostderr -v=3`

**Comment by shinebayar-g** [comment]
+1

`stderr`, `stdout` aren't usable if command fails.  For example, if following command fails pulumi program exists before even `test.stderr.apply` part is invoked.

```ts
const test = new local.Command(`test`, {
  create: 'kubectl get pods',
});

test.stderr.apply((err) => {
  console.log('stderr:');
  console.log(err);
});

```

current workaround: `pulumi up --logtostderr -v=3`

**Comment by itay** [comment]
I've run into a similar issue, which was my external script was failing with some useful output, but it was impossible to see it as part of `local.Command` error, as `stdout` and `stderr` are not set.

This makes debugging pretty much impossible, as you have no idea why the failure happened. In environments where you can't easily run it manually and change things (e.g. automated deployment using GitOps, etc) it makes it even worse.

In Go, I'd recommend that the returned `error` encode stdout/stderr in it, while in other languages it could be in the thrown exception/failed promise information. The developer can extract the information from there if desired.

**Comment by AMKamel** [comment]
Until this is enhanced, maybe a solution is to redirect stderr/stdout into a file at the  remote or local machine, I do that to be able to see a better error message if something failed e.g:
`/usr/local/bin/zx /tmp/s.mjs &2>1 | tee /tmp/s.log`

**Comment by andrekiba** [comment]
Hello, any news about this? It's very hard to understand what is going wrong...especially in an azure devops pipeline or something like this.
