### ISSUE TITLE
Add support for Asset as argument to CopyFile

### ISSUE THREAD

**Issue by rbm-radius** [pulumi/pulumi-command#42]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, CopyFile only takes strings (file system paths) as arguments to describe the local and remote files to be copied. Having support for [Asset](https://www.pulumi.com/docs/intro/concepts/assets-archives/) would allow CopyFile to react to changes to the file as an Asset, and would allow a file upload via CopyFile to work the same way as an upload to S3, which is the same thing conceptually.

**Comment by kwohlfahrt** [comment]
+1, this would be extremely useful (especially if it can handle secrets correctly). There is a PR for this in #25, but it's gone a bit stale.

**Comment by Bessonov** [comment]
@iwahbe Probably, related to or makes https://github.com/pulumi/pulumi-command/issues/23 obsolete
