### ISSUE TITLE
Remote command `environment` field does not actually set the environment.

### ISSUE THREAD

**Issue by alex-hunt-materialize** [pulumi/pulumi-command#48]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The `environment` field does not actually set the environment. This is using pulumi-command version 0.0.3.

### Steps to reproduce

1. Try to run a remote command while setting the environment.
```python3
connection = command.remote.ConnectionArgs(
    host=instance.public_ip,
    user="ubuntu",
    private_key=config.require_secret("ssh_private_key"),
)
command.remote.Command(
    "testvar",
    connection=connection,
    create='echo "${TESTVAR}" > testvar',
    environment={
        "TESTVAR": "asdf1234",
    },
)
```

Expected: The environment variable should be set and accessible when running the command. The contents of the `testvar` file should contain `asdf1234\n`.
Actual: The environment variable seems to not be set, and the contents of the `testvar` file is `\n`.

**Comment by mariospas** [comment]
I can confirm the same issue with golang

**Comment by alex-hunt-materialize** [comment]
@spigell Can we get the documentation updated to say that? The expectation from a user is that the environment would be set _after_ the ssh connection is established.

As 99% of users will not have `AcceptEnv` or `PermitUserEnvironment` set up (since they aren't by default), this feature is misleading at best.

**Comment by CanRau** [comment]
Ran into this myself but have no idea of how to do this, without googling, also would appreciate docs for this, so I might set it during cloudinit.

For now I found a workaround

```ts
const setEnvVarsCommand = new remote.Command("set-env-vars", {
  connection,
  create:
    pulumi.all([
      config.requireSecret("user"),
      config.requireSecret("password"),
    ]).apply(([user, pw]) => "echo export export USER='${user}'\nexport PASSWORD='${pw}' >> ~/.bashrc && source ~/.bashrc"),
});
```

**Comment by thomas11** [comment]
The next release will contain better error handling and docs for this problem. Unfortunately, we were not able to find a way to make remote environments work transparently without extra setup.
