### ISSUE TITLE
Support SSM commands

### ISSUE THREAD

**Issue by johnlabarge** [pulumi/pulumi-command#50]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Similar to terraform I need a ssm provisioner for pulumi commands.  

### Affected area/feature

This would be another bridge for commands/scripts besides ssh.

**Comment by jkodroff** [comment]
@johnlabarge Thanks for submitting this issue.

I'm assuming "ssm" above refers to AWS SSM. If this is correct, would it be possible to use the AWS CLI alongside the existing capabilities of the Pulumi Command provider? Something like:

```typescript
new local.Command("do-ssm-stuff", {
    create: "aws ssm send-command --instance-ids ...",
});
```

**Comment by johnlabarge** [comment]
Correct. I think this will work.

**Comment by johnlabarge** [comment]
1og1op1 it's the exact issue not outside the scope in any way.
