### ISSUE TITLE
remote.Command can't resolve mDNS

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-command#59]
### What happened?

The provider is built with `CGO_ENABLED=0`, which forces the pure Go resolver for DNS.

In the majority of cases this resolver should be fine, however there are a subset of domains the Go resolver can't handle.

### Steps to reproduce

```ts
new remote.Command("test", {connection: {host: "foo.local"}, create: "echo hello"})
```

### Expected Behavior

The "foo.local" mDNS query should not leak to the DNS server.

### Actual Behavior

```
$ GODEBUG=netdns=1 pulumi up
go package net: using cgo DNS resolver
...
Diagnostics:
  pulumi:pulumi:Stack (...):
    error: update failed

    go package net: built with netgo build tag; using Go's DNS resolver

  command:remote:Command (test):
    error: dial tcp: lookup foo.local on 192.168.1.1:53: no such host
```

### Additional context

The user can work around this by resolving the mDNS query in their application code and then passing the IP address to Pulumi. A little kludgy, but it works.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @blampe. It looks like this issue is upstream of https://github.com/golang/go/issues/12524, does that look right? If you are still able to replicate on a modern release of pulumi-command, could you please post a full repro?
