### ISSUE TITLE
Add support for RemoteFile (CopyFile) 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-command#6]
We currently support local command and remote commands. The other use case we may need is copying a local file to a local machine. This can technically be accomplished in awkward forms using the other two, but for simple support, may make sense to support directly.

**Comment by iwahbe** [comment]
@lukehoban and @nimbinatus, I'm assuming that we want `create` to copy the file, and `delete` to do nothing. Does that sound right? I can imagine that delete does nothing, but also that delete removes the created file.

**Comment by lukehoban** [comment]
> I'm assuming that we want create to copy the file, and delete to do nothing. 

Yes, that sounds right to me. We could in principle support opting in to deleting on destroy, but I don’t think that should or needs to be the default behaviour. It’s also easy to couple with a `remote.Command` which removes the file.
