### ISSUE TITLE
Updating remote command hangs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-command#79]
If I provision a `command:remote:Command` with a `create` property, and then change the `create` property and do an update, Pulumi seems to hang forever updating it:

```
 ~   └─ command:remote:Command  updatePythonCmd               updating.    [diff: ~create]
```

The last lines in a verbose log are:

```
I0617 12:55:45.081102   84884 step_executor.go:377] StepExecutor worker(18): applying step update on urn:pulumi:dev::pulumi-ansible-wordpress::command:remote:Command::updatePythonCmd (preview false)
I0617 12:55:45.081118   84884 registry.go:174] GetProvider(urn:pulumi:dev::pulumi-ansible-wordpress::pulumi:providers:command::default::4c6e85c9-6e75-407d-a777-4b5da0154feb)
I0617 12:55:45.081907   84884 provider_plugin.go:972] Provider[command, 0xc0017ea540].Update(ea4c0b4b,urn:pulumi:dev::pulumi-ansible-wordpress::command:remote:Command::updatePythonCmd) executing (#olds=4,#news=2)
```

And a whole lot of RPC marshaling messages.

**Comment by joeduffy** [comment]
This also unfortunately means that if you update a dependency of the command, you will get stuck ☹️

**Comment by greglearns** [comment]
This also seems to be a problem with local commands: 
`++ └─ command:local:Command  create foo if needed  replaced       [diff: ~triggers]`

This appears to occur on 3.35.3 and all earlier versions going back to (at least) 3.31.1 (I stopped trying earlier versions before that). But one strange thing is that I seem to recall this working on earlier versions (e.g. 3.31.1) but now it seems to not work? That makes me feel like I'm missing something.

**Comment by stack72** [comment]
Hi folks

I apologise for the issue here - the company is currently out for the July 4th vacation but as soon as this vacation is over, we can have a look and triage this issue properly and try to determine the cause

Paul

**Comment by greglearns** [comment]
Additional information for whenever people need it:

I just verified that with pulumi version 3.35.3, running `pulumi down -y && pulumi up -y` (a "new" / "fresh" deployment) will hang forever, showing this:
`+   │  ├─ command:local:Command                   FOO create if needed                   creating...`
when this local command runs:
```
    var targzHash;
    try {
      targzHash = getFileHash(app_targzName);
    } catch (e) {
      targzHash = "DOES NOT EXIST " + Math.random();
    }

    const foo = new local.Command(
      "FOO create if needed",
      {
        create: `ls some_file.tar.gz || (npm run build && tar -czvf some_file.tar.gz dist/.)`,
        triggers: [targzHash],
      },
      { parent: this }
    );
```

**Comment by iwahbe** [comment]
@greglearns I am unable to replicate the hang on the current version of command, with either a fresh `pulumi up` or an update caused by `triggers`. The (tested) example `ec2_remote` updates a dependency of a `remote.Command` without hanging.

If you still encounter this problem on an >=v0.8.x version of pulumi-command, please open a new issue.
