### ISSUE TITLE
Print stdout too when there is a failure

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-command#80]
It appears right now that only stderr is emitted to the resource's output stream.  hat could be the right default, to avoid excessive noise in the output, however this makes debugging failures very hard, requiring that you resort to `--logtostderr`. I've tried exporting the `stdout` property as a stack output, but because the resource creation fails, it doesn't get emitted.

At the very least, it seems we should include both stderr and stdout in the output in the case of failure.

I also wonder whether most people will expect the output by default, at least as an ephemeral stream (I know I did, similar to our Docker package). That might be a better default and then we could offer `suppressStdout` and `supressStderr` options.

**Comment by Just-Insane** [comment]
I would also like to be able to view stdout and stderr on resource failure. That would be very helpful with debugging issues.

**Comment by RobCannon** [comment]
This would be incredibly useful.  It is so hard to determine what is going wrong in a lengthy script right now.
