### ISSUE TITLE
Using commands with digital ocean droplet results in error when commands are changed

### ISSUE THREAD

**Issue by mwarger** [pulumi/pulumi-command#89]
### What happened?

In the example repo here (https://github.com/mwarger/pulumi-digital-ocean-testing) I see the following problem:

Running this stack multiple times results in an issue if the `configure-edgedb-password` command is changed. If something about it is altered, the commands will fail.

### Steps to reproduce

Instructions are here:

https://github.com/mwarger/pulumi-digital-ocean-testing#readme

### Expected Behavior

The commands should be rerun - things like finding an existing folder should work.

### Actual Behavior

Running the command will result in errors like this:

```
  command:remote:Command (configure-edgedb-password):
    error: /bin/sh: line 4: /etc/edgedb/env: No such file or directory  // Something like this should work 
    error: /bin/sh: line 5: systemctl: command not found
    error: edgedb error: ClientError: AuthenticationError: authentication failed
    error: /bin/sh: line 9: /etc/edgedb/env: No such file or directory
    error: /bin/sh: line 10: systemctl: command not found
    error: exit status 127
```

### Versions used

```
❯ pulumi about
CLI          
Version      3.35.2
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME          VERSION
command       0.3.2
digitalocean  4.14.0
nodejs        unknown
tls           4.6.0

Host     
OS       darwin
Version  12.4
Arch     arm64

This project is written in nodejs: executable='/Users/mat/.nvm/versions/node/v16.15.0/bin/node' version='v16.15.0'

Current Stack: dev

TYPE                                                URN
pulumi:pulumi:Stack                                 urn:pulumi:dev::pulumi-digital-ocean-testing::pulumi:pulumi:Stack::pulumi-digital-ocean-testing-dev
pulumi:providers:digitalocean                       urn:pulumi:dev::pulumi-digital-ocean-testing::pulumi:providers:digitalocean::default_4_14_0
pulumi:providers:tls                                urn:pulumi:dev::pulumi-digital-ocean-testing::pulumi:providers:tls::default_4_6_0
digitalocean:index/databaseCluster:DatabaseCluster  urn:pulumi:dev::pulumi-digital-ocean-testing::digitalocean:index/databaseCluster:DatabaseCluster::edgedb-postgres-dev
tls:index/privateKey:PrivateKey                     urn:pulumi:dev::pulumi-digital-ocean-testing::tls:index/privateKey:PrivateKey::sshKey
digitalocean:index/sshKey:SshKey                    urn:pulumi:dev::pulumi-digital-ocean-testing::digitalocean:index/sshKey:SshKey::default
digitalocean:index/droplet:Droplet                  urn:pulumi:dev::pulumi-digital-ocean-testing::digitalocean:index/droplet:Droplet::edgedb-droplet-dev
pulumi:providers:command                            urn:pulumi:dev::pulumi-digital-ocean-testing::pulumi:providers:command::default_0_3_2
command:remote:Command                              urn:pulumi:dev::pulumi-digital-ocean-testing::command:remote:Command::configure-edgedb-password


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mwarger
User           mwarger
Organizations  mwarger

Dependencies:
NAME                  VERSION
@pulumi/command       0.3.2
@pulumi/digitalocean  4.14.0
@pulumi/pulumi        3.35.2
@pulumi/tls           4.6.0
@types/node           14.18.21
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
Hi @mwarger, I transferred this to the `pulumi-command` repo because I think the problem may not be specific to Digital Ocean.

I notice that your repro code only configures the `create` action, but leaves [update](https://www.pulumi.com/registry/packages/command/api-docs/remote/command/#update_nodejs) undefined, so I wonder if that might be the issue? Based on the error message and your description of the behavior, perhaps the script isn't idempotent, but is running each time you run an update?

**Comment by mwarger** [comment]
@lblackstone - Thank you for moving this.

> I notice that your repro code only configures the create action, but leaves [update](https://www.pulumi.com/registry/packages/command/api-docs/remote/command/#update_nodejs) undefined, so I wonder if that might be the issue? Based on the error message and your description of the behavior, perhaps the script isn't idempotent, but is running each time you run an update?

I thought of that as well, at one point.  However, the command that's failing is one that shouldn't matter.  It's writing to a directory that exists at all times - that, in particular, shouldn't matter whether it's the first or last time.  

I'm new to this framework, so thank you for your time in replying.

**Comment by lblackstone** [comment]
@jaxxstorm Any idea on this?

**Comment by jon-v** [comment]
Should probably re-test this with [v0.4.1](https://github.com/pulumi/pulumi-command/releases/tag/v0.4.1) since prior to that updates to remote commands were actually executed locally (which would explain the edgedb directory not being found).
