### ISSUE TITLE
Stdout (and stderr) are unexpectedly deleted on a refresh operation

### ISSUE THREAD

**Issue by gpduck** [pulumi/pulumi-command#94]
### What happened?

We have a script we're running using the command resource that outputs data about the objects that it is creating. We then consume and parse the stdout output to pass this information into dependent resources. However when we run a refresh on the stack, the stdout and stderr output values are cleared and then because the Command resource already exists the output is never available again unless we force the resource to be recreated.

### Steps to reproduce

Create a command resource that outputs a string value to stdout.
Create another resource that uses stdout from the command resource.
Run a refresh.
The dependent resource will no longer have a value from stdout.

### Expected Behavior

Either the refresh should not delete stdout and stderr, or the Command resource needs to have a "Get" command to output the current value of the resource so that refresh will update stdout and stderr instead of deleting them.

### Actual Behavior

stdout and stderr are deleted on pulumi refresh

### Versions used

The pulumi-command version used was 0.3.2, I don't have access to the project at the moment to get the other versions. Let me know if I need to provide them and I'll update when I can.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment]
@lukehoban Is there any chance that this is by design, e.g. potentially to keep secrets out of the state file?
