### ISSUE TITLE
Support using SSH agent for authentication

### ISSUE THREAD

**Issue by kwohlfahrt** [pulumi/pulumi-command#96]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

My instance allows SSH access via a pre-existing public key, which I have added to my locally running SSH agent (with `ssh-add`), so I can just `ssh example.com` without specifying or configuring a private key.

`remote.Command` does not detect that an SSH agent is available, so it fails with the following error:
```
  command:remote:CopyFile (master.sh):
    error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

If the environment variable `$SSH_AUTH_SOCK` is defined (or perhaps via an input option), the connection should create a new SSH client using the [agent package](https://pkg.go.dev/golang.org/x/crypto@v0.0.0-20220622213112-05595931fe9d/ssh/agent#NewClient), and use this to respond, as described [here](https://blog.ralch.com/articles/golang-ssh-connection/#ssh-agent).

**Comment by danielrbradley** [comment]
Thanks for the detail – this looks like a good addition. We'll add it to the provider's backlog, but if you're keen to add this feature yourself we would welcome the PR!

**Comment by protometa** [comment]
It might also be desirable to get default connection options from the user/system ssh config file with [ssh_config](https://pkg.go.dev/github.com/kevinburke/ssh_config#section-readme).
